### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pjmangaming** [xnti/discord-nitro-generator#5]
19/04/2021 [6:22:29 pm] [INFO]: Nitro Generator by antibioticTR
C:\Users\muzam\Downloads\discord-nitro-generator-master (1)\discord-nitro-generator-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133
    const invalidToken = new DJSError(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\muzam\Downloads\discord-nitro-generator-master (1)\discord-nitro-generator-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\muzam\Downloads\discord-nitro-generator-master (1)\discord-nitro-generator-master\node_modules\discord.js\src\client\Client.js:223:21)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}
Press any key to continue . . .

**Comment by pjmangaming** [comment]
mb on that issue but this one is what happen after i run it


19/04/2021 [6:36:56 pm] [INFO]: Nitro Generator by antibioticTR
Invalid: HhPFumOnmufeT3Wx : Searching!
Rate limit reached! Switched proxy
Rate limit reached! Switched proxy
Invalid: 6TcTaA1KLMFiAHBn : Searching!
Invalid: rhaB8KSHJaaVJ04U : Searching!
Rate limit reached! Switched proxy
Rate limit reached! Switched proxy
Rate limit reached! Switched proxy
Rate limit reached! Switched proxy
Rate limit reached! Switched proxy
Invalid: GjG8lQhH6erYqNwg : Searching!
Invalid: kTjUZleJHPUfgYKo : Searching!
Connection error: switching proxy
Invalid: dMuk2breS40aCrtc : Searching!
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
Connection error: switching proxy
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:211:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Press any key to continue . . .

**Comment by xnti** [comment]
Hello this error happens because of TCP conversation abruptly closed its end of the connection. Please try this article to fix it: https://peterthaleikis.com/posts/how-to-fix-throw-er-unhandled-error-event.html

For any further errors please hit me up I will research it too...

**Comment by pjmangaming** [comment]
will do

**Comment by xnti** [comment]
Thank you @pjmangaming,
I will close the issue right now, for further errors please re-open a new one 👍🏻
