### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by LxbEz** [xnti/discord-nitro-generator#8]
It shows up this error:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- C:\Users\artuf\OneDrive\Escritorio\discord-nitro-generator-master\app.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\artuf\OneDrive\Escritorio\discord-nitro-generator-master\app.js:16:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
Also I would want to tell me how can I find that proxies, I have some pasted in proxies, but i dont know if they work.

**Comment by Radu-wq** [comment]
> It shows up this error:
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'request'
> Require stack:
> 
> * C:\Users\artuf\OneDrive\Escritorio\discord-nitro-generator-master\app.js
>   ←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
>   ←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
>   ←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
>   at Object. (C:\Users\artuf\OneDrive\Escritorio\discord-nitro-generator-master\app.js:16:17)
>   ←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
>   ←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
>   ←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
>   ←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
>   code: ←[32m'MODULE_NOT_FOUND'←[39m,
>   requireStack: [
>   Also I would want to tell me how can I find that proxies, I have some pasted in proxies, but i dont know if they work.
You have to install all modules using "npm install". 
Installing request would be "npm install request".

**Comment by xnti** [comment]
Hello @LxbEz ,
as I see @Radu-wq answered your question so I am closing this issue post.
