### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tzt345** [xnti/discord-nitro-generator#9]
Plz fix it ):
![Screenshot_2021-08-06-02-21-08-81](https://user-images.githubusercontent.com/83703996/128402054-fa7ec50d-605f-4c45-b5ef-15b4f60bbb0c.png)
& This
![Screenshot_2021-08-06-02-26-21-24](https://user-images.githubusercontent.com/83703996/128402090-342dd7c0-8a40-4eca-9df2-75934f8eec0b.png)

**Comment by FFisher190** [comment]
> Plz fix it ):
> ![Screenshot_2021-08-06-02-21-08-81](https://user-images.githubusercontent.com/83703996/128402054-fa7ec50d-605f-4c45-b5ef-15b4f60bbb0c.png)
> & This
> ![Screenshot_2021-08-06-02-26-21-24](https://user-images.githubusercontent.com/83703996/128402090-342dd7c0-8a40-4eca-9df2-75934f8eec0b.png)

Its A Connection Error, Make Sure To Stop All Incoming Requests Before The Connection

For more detail check this out - [https://stackoverflow.com/questions/10814481/how-to-debug-a-socket-hang-up-error-in-nodejs/11542134#11542134](Debug Socket Hang Up)

**Comment by xnti** [comment]
Hi @FFisher190,
Sorry for the late reply, I see that you found your answer, if your problem still persists, please do not hesitate to open a new topic :).

**Comment by tzt345** [comment]
> > Plz fix it ):
> > ![Screenshot_2021-08-06-02-21-08-81](https://user-images.githubusercontent.com/83703996/128402054-fa7ec50d-605f-4c45-b5ef-15b4f60bbb0c.png)
> > & This
> > ![Screenshot_2021-08-06-02-26-21-24](https://user-images.githubusercontent.com/83703996/128402090-342dd7c0-8a40-4eca-9df2-75934f8eec0b.png)
> 
> Its A Connection Error, Make Sure To Stop All Incoming Requests Before The Connection
> 
> For more detail check this out - https://stackoverflow.com/questions/10814481/how-to-debug-a-socket-hang-up-error-in-nodejs/11542134#11542134

I don't get it??

**Comment by tzt345** [comment]
@FFisher190
